basic:
    name: 'https://www.leadingedgespecializeddentistry.com/'
    environments:
        production: 'https://www.leadingedgespecializeddentistry.com/'
        staging: 'https://zr37se0g9n.wpdns.site/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: null
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /bill-pay
        - /patient-resources
        - /practice-transitions
        - /oral-surgery
        - /endodontics
        - /periodontics
        - /prosthodontics
        - /location
        - /doctors
        - /services
        - /blog/root-canal-therapy
        - /blog/wisdom-teeth-faqs
        - /blog/what-is-endodontics
        - /blog
        - /news
        - /saliva-score
        - /careers
        - /privacy-policy
        - /hipaa-policy
        - /accessibility-statement
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
